name: scbrf
description: Scarborough is a Electron clone of Livid's Planet.
publish_to: 'none'
version: 0.0.2+3

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  meta: '>=1.1.0 <2.0.0'
  logger: ^1.1.0
  multicast_dns: ^0.3.2+2
  http: ^0.13.5
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  cached_network_image: ^3.2.2
  just_audio: ^0.9.29
  audio_service: ^0.18.7
  get_it: ^7.2.0
  image_picker: ^0.8.4+9
  uuid: 3.0.6
  path_provider: ^2.0.11
  path: ^1.8.2
  markdown: ^6.0.1
  cupertino_icons: ^1.0.2
  webview_flutter: ^3.0.4
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.10.0"
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
